#!/bin/bash

N=$1
if [ -z "$N" ]; then
    N=0
fi
N=$(( N + 1 ))

# TODO: Parameterize patch directory
patch=$(ls -t ~/incoming-patches/*PATCH_*.mbox 2>/dev/null| head -n ${N} | tail -n 1)

if [ -z "${patch}" ]; then
    exit 0
fi

# TODO: Test apply the patch?

echo $patch
git am $patch
# TODO: Handle error; rollback branch to known good state

# TODO: Register the time landed
if [ $? -eq 0 ]; then
    mv $patch ~/incoming-patches/Landed/
else
    git am --abort
fi

