#!/usr/bin/env python
# coding: utf-8

usage = '''
%prog [options] <MonthYEAR>
'''

import os
import sys
import glob
import json
import urllib
import string
from datetime import datetime

def load_file(fname):
    filename = os.path.expanduser(fname)
    with open(filename, 'r') as f:
        text = f.read()
    return text

if __name__ == "__main__":
    sensing_dir = "~/Samsung/Sensing/" # TODO
    templates_dir = "~/src/Autotwiki/autotwiki/templates"
    today = datetime.strftime(datetime.now(), "%Y-%m-%d")
    quarter = "2014-Q3" # TODO

    cairo_html   = load_file("%s/%s/%s.html" %(sensing_dir, quarter, "cairo"))
    efl_html     = load_file("%s/%s/%s.html" %(sensing_dir, quarter, "efl"))
    wayland_html = load_file("%s/%s/%s.html" %(sensing_dir, quarter, "wayland"))
    xorg_html    = load_file("%s/%s/%s.html" %(sensing_dir, quarter, "xorg"))

    # TODO: Cleanup html
    # Strip HTML comments
    # Strip all classes from elements
    # Strip out all spans
    # Strip out all Page Permissions sections
    # Delete the WYSIWYG_PROTECTED lines
    # Move all Upcoming Events section to the end
    # Reformat the headers
    # Drop the Development/Stable headers
    # Remove any blank <p>&nbsp;</p> lines
    # Move all the Final Thoughts sections to the end

    page_params = {
        'date': today,
        'cairo_content': cairo_html,
        'efl_content': efl_html,
        'wayland_content': wayland_html,
        'xorg_content': xorg_html,
        'events': ''  # TODO
        }

    text = load_file(templates_dir + "/linuxjournal.html")
    text = string.Template(text).substitute(page_params)

    print text
