#!/bin/bash
#
# Copyright © 2016 Samsung Electronics, Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PATCHERY=$(which patchery-status)
if [ -z "$PATCHERY" ]; then
    echo "Prerequisite 'patchery-status' is not present in path" 2>&1
    exit 1
fi
#if [ ! -d "$1" ]; then
#    echo "Usage:  $0 <repository> [begin-date] [end-date]" 2>&1
#    exit 1
#fi
if [ ! -z "$2" ] && [ $2 != 'Beginning' ]; then
    # TODO: Convert to a timestamp
    begin="--since=$2"
fi
if [ ! -z "$3" ] && [ $3 != 'End' ]; then
    # TODO: Convert to a timestamp
    end="--until=$3"
fi

# HACK: Currently patchery-status only returns data for the past week
$PATCHERY | while read line; do echo "1 $line"; done


