#!/bin/bash
#
# Copyright © 2014 Samsung Electronics, Ltd.
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ ! -d "$1" ]; then
    echo "Usage:  $0 <repository> [begin-date] [end-date]" 2>&1
    exit 1
fi
cd $1
if [ ! -z "$2" ] && [ $2 != 'Beginning' ]; then
    begin="--since=$2"
fi
if [ ! -z "$3" ] && [ $3 != 'End' ]; then
    end="--until=$3"
fi

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

author=
committer=
for line in $(git log --pretty=fuller ${begin} ${end}); do
    if [[ ${line} == Author:* ]]; then
	author=$(echo ${line} | cut -d: -f2- | sed 's/^ *//')
    elif [[ ${line} == Commit:* ]]; then
	committer=$(echo ${line} | cut -d: -f2- | sed 's/^ *//')
    elif [[ ${line} == "commit "* ]] && [[ ! -z "${committer}" ]]; then
	if [ ${author} != ${committer} ]; then
	    echo ${committer}
	fi
	author=
	committer=
    fi
done | sort -b | uniq -c

IFS=${SAVEDIFS}